# Generated by Django 4.2.7 on 2025-09-20 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('es', 'Español'), ('en', 'English')], max_length=2, verbose_name='Idioma')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre traducido')),
                ('descripcion', models.TextField(verbose_name='Descripción traducida')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='productos.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Traducción de Producto',
                'verbose_name_plural': 'Traducciones de Productos',
                'ordering': ['product', 'language'],
                'unique_together': {('product', 'language')},
            },
        ),
    ]
