# Generated by Django 4.2.7 on 2025-10-17 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_producttranslation'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='formatos',
            field=models.JSONField(default=list, help_text='Lista de formatos disponibles para este producto', verbose_name='Formatos disponibles'),
        ),
    ]
